# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SHIELD
email: info@shield-h2020.eu
description: > # this means to ignore newlines until "baseurl:"
  SHIELD proposes a NFV based solution for dynamically deploying virtual
  security infrastructures into ISP and corporate networks
baseurl: "/shield-h2020" # the subpath of your site, e.g. /blog
url: "https://torsec.github.io" # the base hostname & protocol for your site
twitter_username: shield_h2020
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima

collections:
  news:
    output: true
    permalink: /news/:year-:month-:day-:title.html
  partners:
    output: true
    permalink: /about/consortium/:title.html

google_analytics_id: UA-84944136-1

sass:
  style: :compressed

dataurl: "https://data.shield-h2020.eu"

future: true
